// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkK5CmUkQd6EukkIzLOyGu7bUrrmmpIHc',
    appId: '1:295293393618:web:8d69d6e379b117eac3ab0b',
    messagingSenderId: '295293393618',
    projectId: 'winr-9c11f',
    authDomain: 'winr-9c11f.firebaseapp.com',
    storageBucket: 'winr-9c11f.firebasestorage.app',
    measurementId: 'G-L2TGT1VK2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1MPnrDDnuEzsjgm1utGhxcb3bmnbZWBI',
    appId: '1:295293393618:android:3d7c67442ffa0bc9c3ab0b',
    messagingSenderId: '295293393618',
    projectId: 'winr-9c11f',
    storageBucket: 'winr-9c11f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4D6pEvvtqWX-o10QaEn7RjEjMrjLuNaE',
    appId: '1:295293393618:ios:8cc52fb84e3668fac3ab0b',
    messagingSenderId: '295293393618',
    projectId: 'winr-9c11f',
    storageBucket: 'winr-9c11f.firebasestorage.app',
    iosBundleId: 'com.example.winrFlutterSdk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4D6pEvvtqWX-o10QaEn7RjEjMrjLuNaE',
    appId: '1:295293393618:ios:684f8cdb32bfc5d3c3ab0b',
    messagingSenderId: '295293393618',
    projectId: 'winr-9c11f',
    storageBucket: 'winr-9c11f.firebasestorage.app',
    iosBundleId: 'com.avafli.winr.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkK5CmUkQd6EukkIzLOyGu7bUrrmmpIHc',
    appId: '1:295293393618:web:4780b7a28ae22ba4c3ab0b',
    messagingSenderId: '295293393618',
    projectId: 'winr-9c11f',
    authDomain: 'winr-9c11f.firebaseapp.com',
    storageBucket: 'winr-9c11f.firebasestorage.app',
    measurementId: 'G-6LJ1961LG8',
  );
}
